network:
  port: 8080
hubs:
  static:
    # The directory where static files belong
    path: "/var/www/html/"
    # The desired host which will be served (not implemented)
    host: "example.com"
    # Apache like rules
    rewrite_rules: |
      RewriteEngine On
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
      RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
      RewriteRule ^ - [L]
      RewriteRule ^ /index.html
    # Add custom headers to reponses (not implemented)
    headers:
      "Server": "sthub"
  configuration:
    host: "example.com"
    cache: true # (not implemented)
    providers:
      env:
        prefix: "MYAPI"
      dotenv: # (not implemented)
        path: "./.env"
        hotreload: true
